version: '3'
services:

  db:
    restart: always
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: e-commerce
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_TCP_PORT: 3307
      MYSQL_ROOT_HOST: localhost
    ports:
      - "3307:3307"